spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/assistant?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  redis:
    host: 192.168.75.132
    port: 6379
  security:
    basic:
      enabled: true
    user:
      name: admin
      password: 123
mybatis:
  type-aliases-package: com.assistant.pojo
  mapper-locations: classpath:mybatis/*.xml
  configuration:
    map-underscore-to-camel-case: true
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
